repos:
-   repo: local 
    hooks:
    - id: ruff
      name: ruff
      entry: ruff --fix
      language: system
      types: [python]
    - id: ruff-format
      name: ruff format
      entry: ruff format
      language: system
      types: [python]
    - id: mypy
      name: MyPy
      entry: mypy
      language: system
      types: [python] 
