[tool.poetry]
name = "semantle-he"
version = "0.1.0"
description = "A Hebrew version of Semantle."
authors = ["Itamar Shefi <itamarshefi@gmail.com>"]
license = "GNU v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
redis = ">=5.0.1,<5.1.0"
fastapi = ">=0.103.1,<0.104.0"
jinja2 = ">=3.1.2,<3.2.0"
motor = ">=3.3.1,<3.4.0"
numpy = ">=1.26.0,<1.27.0"
omegaconf = ">=2.3.0,<2.4.0"
pymongo = {version = ">=4.5.0,<4.6.0", extras = ["srv"]}
uvicorn = {version = ">=0.23.2,<0.24.0", extras = ["standard"]}
pydantic = ">=2.4.1,<2.5.0"
gensim = ">=4.3.2,<4.4.0"
gdown = ">=4.7.1,<4.8.0"
google-auth = ">=2.23.1,<2.24.0"
python-dateutil = "2.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
